spring:
  datasource:
    url: jdbc:mysql://localhost:3306/donatekaro?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      file-size-threshold: 1KB
server:
  port: 8081
